apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: feedbacklens
spec:
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP