apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: feedbacklens-gateway
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - feedbacklens
  selector:
    matchLabels:
      app: gateway
  podMetricsEndpoints:
    - path: /metrics
      port: http
      interval: 15s