apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: feedbacklens-monitor
  namespace: feedbacklens
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gateway
  endpoints:
    - port: "8000"
      path: /metrics
      interval: 30s